service: aws-node-iot-event

frameworkVersion: ">=1.5.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3

functions:
  log:
    handler: handler.init
    events:
      - iot:
          name: "iotOrchestrator"
          sql: "SELECT * FROM 'orch_topic'"
          enabled: true
          description: "An IoT handler to orchestrate an event"
	  sqlVersion: "beta"
